# Main entrypoint of the workflow.

# Quality process of reads
rule qc:
	input:
		"""
		r1=
		r2=
		"""
	output:
		"""
		"""
	shell:
		"""
		"""
# Assembly contigs with Spades or Megahit
rule qc:
	input:
		"""
		r1=
		r2=
		"""
	output:
		"""
		"""
	shell:
		"""
		"""

# Check contigs qc QUAST
rule qc:
	input:
		"""
		r1=
		r2=
		"""
	output:
		"""
		"""
	shell:
		"""
		"""

# Create figures, R?
rule qc:
	input:
		"""
		r1=
		r2=
		"""
	output:
		"""
		"""
	shell:
		"""
		"""
