name: contignyzer

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - snakemake
  - spades
  - megahit
  - quast
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
      - jinja2  # For future HTML report option
  - coreutils  # for GNU time