samples:
  chicken_gut_01:
    R1: "data/raw/chicken_gut_01_R1.fastq.gz"
    R2: "data/raw/chicken_gut_01_R2.fastq.gz"
  chicken_gut_02:
    R1: "data/raw/chicken_gut_02_R1.fastq.gz"
    R2: "data/raw/chicken_gut_02_R2.fastq.gz"

kmer_sets:
  kset1: [21, 33, 55]
  kset2: [27, 37, 47]

assemblers: [spades]

threads: 8